---
- name: Provisioning webservers group
  hosts: webservers
  gather_facts: false
  vars:
    # Whether to reboot when needed during unattended upgrades.
    security_autoupdate_reboot: "true"
    # The time to trigger a reboot, when needed, if security_autoupdate_reboot is set to true. In 24h "hh:mm" clock format.
    security_autoupdate_reboot_time: "03:00"
  roles:
    - wait_for_connection
    - packages
    - sysctl
    - docker
    - deployer
    - firewall
    - security
    - auditd
    - geerlingguy.swap
    - reboot_if_needed
