---
- name: Update SSH configuration to be more secure
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: "0644"
  loop:
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "PermitRootLogin", value: "prohibit-password" }
    - { key: "Port", value: "22" }
    - { key: "UseDNS", value: "no" }
    - { key: "PermitEmptyPasswords", value: "no" }
    - { key: "ChallengeResponseAuthentication", value: "no" }
    - { key: "GSSAPIAuthentication", value: "no" }
    - { key: "X11Forwarding", value: "no" }
    - { key: "MaxAuthTries", value: "3" }
    - { key: "ClientAliveInterval", value: "300" }
    - { key: "ClientAliveCountMax", value: "2" }
    - { key: "LoginGraceTime", value: "20" }
    - { key: "AllowUsers", value: "{{ ssh_allowed_users | default('ubuntu deployer') }}" }
    - { key: "Protocol", value: "2" }
    - { key: "MaxSessions", value: "2" }
  notify:
    - Restart ssh

- name: Configure Fail2ban jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart fail2ban

- name: Ensure fail2ban is started and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Update unattended-upgrades configuration to be more secure
  ansible.builtin.lineinfile:
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: "^(\/\/)?{{ item.key }} "
    line: "{{ item.key }} \"{{ item.value }}\";"
    state: present
    mode: "0644"
  loop:
    - { key: "Unattended-Upgrade::Automatic-Reboot", value: "{{ security_autoupdate_reboot }}" }
    - { key: "Unattended-Upgrade::Automatic-Reboot-Time", value: "{{ security_autoupdate_reboot_time }}" }
  when: security_autoupdate_reboot == "true"
